name: "Godot CI/CD"
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  test-game:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
          unzip Godot_v4.6-stable_linux.x86_64.zip
          mv Godot_v4.6-stable_linux.x86_64 godot
          chmod +x godot

      - name: Run GUT Tests
        run: |
          ./godot --headless -s addons/gut/gut_cmdln.gd -gdir=test -ginclude_subdirs -gexit

  export-game:
    name: Export Game
    needs: test-game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Game
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6-stable/Godot_v4.6-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          cache: true
          use_preset_export_path: true

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Windows 
          path: ./Windows Desktop/kh.exe

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: Linux Build
          path: ./Linux/kh.x86_64
