name: "Godot Export"
on:
  push:
    branches:
      - master
      - main

jobs:
  export-game:
    name: Export Game
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Game
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz
          relative_project_path: ./
          archive_output: false
          cache: true
          use_preset_export_path: true

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: Windows Build
          path: ./*.zip

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: Linux Build
          path: ./Linux/*
